### ISSUE TITLE
Corrigir sequência de links no rodapé

### ISSUE THREAD

**Issue by aalvesjr** [crgimenes/Go-Hands-On#27]
### ToDo
  - [ ] Exemplo `Configurando` deveria ter um link para `Workspace` e não para `Ola mundo`;
  - [ ] Exemplo `Ola Mundo` deveria ter um link para `Workspace` e não para Configurando`;
  - [ ] Exemplo `Goroutines Waitgroup` deveria retornar para `Goroutines` e não para `Error`;
  - [ ] Exemplo `Select` deveria retornar para `WaitGroup` e não para `Goroutines`;
  - [ ] Exemplo `Http` deveria ter o link para `RegExp` e não para `Tratando Sinais`;
  - [ ] Adicionar links dentro do exemplo de `RegExp`;
  - [ ] No exemplo de `Tratando sinais`, alterar link para retornar para exemplo de `RegExp`;

> Talvez adotar um padrão para os links como: "tudo minúscula" ou "sempre começar com maiúscula"

Essa issue só faz sentido ser trabalhada de acordo com o definido em https://github.com/crgimenes/Go-Hands-On/issues/26

**Comment by crgimenes** [comment]
Corrigi os links e adicionei instruções CONTRIBUTING.md
